workflows:
  android-workflow:
    name: Android APK Build
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk