workflows:
  android-build:
    name: MWinPlay Android Build
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      vars:
        PACKAGE_NAME: "com.mwinplay.app"
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - your_mwinplay03@gmail.com
